### ISSUE TITLE
Can't generate a PDF file.

### ISSUE THREAD

**Issue by Akhenaton** [JustCarmen/fancy_treeview_pdf#3]
Hi Carmen,

I can't generate a PDF file... Here is my log : 

error	/var/www/webtrees/includes/session.php:193 /var/www/webtrees/modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 **fopen(/media/LINUX-CLOUD/webtrees/data/ftv_cache/1-M2472-1420647246.png): failed to open stream: No such file or directory**
#0 unknown:unknown ErrorException("/var/www/webtrees/modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 **fopen(/media/LINUX-CLOUD/webtrees/data/ftv_cache/1-M2472-1420647246.png): failed to open stream: No such file or directory")**
#1 /modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 fopen('/media/LINUX-CLOUD/webtrees/da…', 'rb')
#2 /modules_v3/fancy_treeview_pdf/mpdf/Tag.php:3271 _getImage('https://UNDISCLOSED.net/media/LIN…', true, true, '/media/LINUX-CLOUD/webtrees/da…', false)
#3 /modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:16543 OpenTag('IMG', [array], [array], 29)
#4 /modules_v3/fancy_treeview_pdf/app/Template/PdfTemplate.php:88 WriteHTML('Descendants de <span class…', 2, true, false)
#5 /modules_v3/fancy_treeview_pdf/module.php:120 pageBody()
#6 /module.php:26 modAction('write_pdf')

It's weird, because the file "1-M2472-1420647246.png" **IS** in that directory...

Any tips ? Thank you ! 

[EDIT] Got also this one now : 

error	/var/www/webtrees/includes/session.php:193 /var/www/webtrees/modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 **fopen(/media/LINUX-CLOUD/webtrees/data/ftv_cache/undefined)**: failed to open stream: No such file or directory
#0 unknown:unknown ErrorException("/var/www/webtrees/modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 f**open(/media/LINUX-CLOUD/webtrees/data/ftv_cache/undefined**): failed to open stream: No such file or directory")

**Comment by JustCarmen** [comment]
Can you generate a pdf file from a fancy treeview page without images? and does it work with other images but the one mentioned here? It could be the image is corrupt. Best to clear the ftv_cache folder first before testing.

**Comment by Akhenaton** [comment]
Hi Carmen, thank you for your quick response !

I can't neither generate a PDF file from a fancy treeview page without images and it does not work with other images, and yes i've cleared the cache folders before testing.
Same error : 

> error	/var/www/webtrees/includes/session.php:193 /var/www/webtrees/modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 fopen(/media/LINUX-CLOUD/webtrees/data/ftv_cache/undefined): failed to open stream: No such file or directory

Weird because the fancy treeview module works very nicely, with or without images and renders well.

Could it be an URL problem in the "mpdf.php" file ? I see from line 11806 in it : 
```
			if ($orig_srcpath && $this->basepathIsLocal && $check = @fopen($orig_srcpath, "rb")) {
				fclose($check);
				$file = $orig_srcpath;
				$data = file_get_contents($file);
				$type = $this->_imageTypeFromString($data);
			}
			if (!$data && $check = @fopen($file, "rb")) {
				fclose($check);
				$data = file_get_contents($file);
				$type = $this->_imageTypeFromString($data);
			}
			if ((!$data || !$type) && !ini_get('allow_url_fopen')) { // only worth trying if remote file and !ini_get('allow_url_fopen')
				$this->file_get_contents_by_socket($file, $data); // needs full url?? even on local (never needed for local)
				if ($data) {
					$type = $this->_imageTypeFromString($data);
				}
			}
			if ((!$data || !$type) && function_exists("curl_init")) { // mPDF 5.7.4
				$this->file_get_contents_by_curl($file, $data);  // needs full url?? even on local (never needed for local)
				if ($data) {
					$type = $this->_imageTypeFromString($data);
				}
			}

```
some url comments and questions.... but i'm not a programmer and i don't know anything about the PHP language....

**Comment by JustCarmen** [comment]
I can't figure out what is wrong, but I don't think this is related to the images, because you say you have the same problem rendering a pdf from a page without images. I need to know if there is made a pdf file at all.

Test this by commenting this line in the file module.php:

Put two slashes before line 137. You can do this with notepad for example.
>//File::delete(dirname($file));

Before the pdf file is ready to download it is saved temporarily on the server in the folder data/ftv_pdf_tmp.

Try to render a pdf file (from a page without images) and then look into this folder to see if it contains a pdf file.

If the pdf file is not there, then further debugging is necessary. You are running webrees from a local server right? Then you need to this test yourself, otherwise I can do it for you.

You need firefox with the firebug add-on installed. Open firebug with F12 and then click the console tab. Then click on the ftv-pdf button. Firebug will output a line with starts with 'POST'. Click on the +-icon before this line and check the 'answer'-tab. The answer tab should contain an error message. Post it here. If there is no answer tab, then check the 'Post'-tab. It should contain the html output which is the preparation of the pdf file. Does it? or does it show an error message. If so, post the message here.

**Comment by Akhenaton** [comment]
I am very sorry, i made a mistake,  but **rendering a pdf from a page without any images works perfectly well** ! my bad....

It's only when there is one or more image(s) that it fails. (I've tried with different images and it fails each time)

Now, i tried on a page with some images and the firebug add-on but Firebug doesn't output a line wich starts with 'POST'. Should i put here all the lines i get ?

Again, thank you very much !

**Comment by JustCarmen** [comment]
Sorry for the delay but I was busy the last few days. But slept over it a few nights and I think I've found the solution for your problem. For some reason mpdf isn't able to find the correct image path or can't reach the images at the server for some reason. I don't know why it doesn't work in your case but I think we can avoid this by embedding the images in the fancy treeview page in stead of loading them from an image path. In that case there is no need for mpdf to load the images from the server but it can use the images already embedded in the FTV-page.

I would like you to test this out before I make this change final. 

[test ftv-pdf-images.zip](https://github.com/JustCarmen/fancy_treeview_pdf/files/614118/test.ftv-pdf-images.zip)

In the zip you will find two files. 
- Copy the file FancyTreeviewClass to the folder modules_v3/fancy_treeview/app
- Copy the file pdf.js to the folder modules_v3/fancy_treeview_pdf/js

Both replacing the original files with the same name in those folders.

Let me know if it works. If it does I will need to do some more tweaks to the code before I can make this final in the repository, but for this test the changes I've made so far will do.

**Comment by Akhenaton** [comment]
Hi Carmen,

Thank you for taking care of my problem. I really appreciate your help !
But still, after the little changes of these 2 files, it doesn't work... Here what i get now in the log : 

> error
> /var/www/webtrees/includes/session.php:193 /var/www/webtrees/modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 fopen(mediafirewall.php?mid=M1859&amp;thumb=1&amp;ged=tree1&amp;cb=12766606): failed to open stream: No such file or directory
> #0 unknown:unknown ErrorException("/var/www/webtrees/modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 fopen(mediafirewall.php?mid=M1859&amp;thumb=1&amp;ged=tree1&amp;cb=12766606): failed to open stream: No such file or directory")
> #1 /modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:11806 fopen('mediafirewall.php?mid=M1859&th…', 'rb')
> #2 /modules_v3/fancy_treeview_pdf/mpdf/Tag.php:3271 _getImage('https://UNDISCLOSED.net/webtrees/…', true, true, 'mediafirewall.php?mid=M1859&th…', false)
> #3 /modules_v3/fancy_treeview_pdf/mpdf/mpdf.php:16543 OpenTag('IMG', [array], [array], 315)
> #4 /modules_v3/fancy_treeview_pdf/app/Template/PdfTemplate.php:88 WriteHTML('<h2>Descendants de <span class…', 2, true, false)
> #5 /modules_v3/fancy_treeview_pdf/module.php:120 pageBody()
> #6 /module.php:26 modAction('write_pdf')

Could it be related to the "mediafirewall" thing ?
In the /data/ftv_cache folder, there is all the images (png & jpg) corresponding to the pages of the fancytreeview...

**Comment by Akhenaton** [comment]
P.S. If it's more easy for you to debug, i can give you a full access with a login/pass as administrator of my web, and put the NL language in place for you (it's in french actually)
Just tell me and give me a private mail address where i can send you your credentials and the URL of my site. (I have my own server at home, and it's private, only for the family actually)

**Comment by JustCarmen** [comment]
Yes, please. That would certainly help because I can't reproduce your problem at my own server (not even with a completely private tree), which makes it hard to debug. You can find my email address in my profile.

**Comment by Akhenaton** [comment]
Done, thank you !

**Comment by Akhenaton** [comment]
To be precise, I still stay with the 2 files changes of your "test ftv-pdf-images.zip"
... and see you are working hard !  :+1:

**Comment by JustCarmen** [comment]
I have, and I think I'm done now. I've just send you an email. After your confirmation I will post the solution here.

**Comment by JustCarmen** [comment]
We've solved this issue. The problem was caused by the use of gif images, which were not supported by the fancy treeview module. 

Most people won't use gif images unless they need animated images, because of its poor quality. The best advice I can give you is to convert these images to png (png supports transparency). There are many tools available on the web for free which will allow you to bulk convert a set of images from any format to any format.

But to prevent this problem in the future I have made some alterations to the code to support gif images. The fix is done inside the (main) Fancy Treeview module:

https://github.com/JustCarmen/fancy_treeview/commit/a9618924355dbbf74bc6300aa0203c18661f4a40

Note that although this code change makes support for gif files possible, gif transparency is still not supported. Gif transparency isn't supported anywhere in webtrees. If you want to use transparent images in webtrees there is no alternative then convert the images to png.
